// Legacy rich content — kept for any other pages that may reference it
export const PATHWAY_RICH_CONTENT = {
  home_daycare_nursery: {
    why: "This pathway fits someone who wants consistent care, steady monthly income, and deep relationships with a small group of families.",
    become: "A home daycare or nursery can become a sustainable recurring-revenue business with the right licensing path, insurance coverage, parent policies, daily rhythm, and pricing structure.",
    phase1: "Your first step is clarity. Before you open your doors, you need to define your model, ages served, schedule, space setup, pricing, parent expectations, and business protection needs.",
  },
  part_time_nursery: {
    why: "This pathway fits someone who wants a structured childcare offering without committing to full-time care.",
    become: "A part-time nursery can serve families who need a few reliable days per week, a morning program, or a school-day rhythm.",
    phase1: "Your first step is to define the schedule, ages served, tuition structure, enrollment expectations, and parent policies.",
  },
  drop_in_care: {
    why: "This pathway fits someone who is drawn to flexibility, backup care, occasional care, or serving families who do not need a full-time spot.",
    become: "Drop-in care can become a flexible childcare offer with clear boundaries, strong policies, and simple booking systems.",
    phase1: "Your first step is to define exactly when drop-in care is available, how parents book, how payment works, what ages you serve, and what policies protect your home and time.",
  },
  kids_classes: {
    why: "This pathway fits someone who loves planning activities, teaching, movement, music, art, sensory play, literacy, or enrichment.",
    become: "Kids classes can become a playful local business built around sessions, workshops, pop-ups, birthday parties, or seasonal programs.",
    phase1: "Your first step is to choose your class theme, age range, session length, location, pricing, booking system, and parent experience.",
  },
  mommy_and_me: {
    why: "This pathway fits someone who enjoys parent-child connection, community building, and creating warm spaces for moms, caregivers, and young children.",
    become: "A Mommy & Me program can become a community-centered class, play session, or gathering space where families build connection.",
    phase1: "Your first step is to define the age range, session flow, parent role, location, pricing, and community experience.",
  },
  playgroup_open_play: {
    why: "This pathway fits someone who loves hosting, gathering families, and creating relaxed spaces for children to play.",
    become: "A playgroup or open play model can become a simple local offer built around recurring sessions, seasonal gatherings, or community events.",
    phase1: "Your first step is to define your space, safety expectations, parent supervision rules, session times, pricing, capacity, and flow.",
  },
  homeschool_pod: {
    why: "This pathway fits someone who is drawn to school-age children, teaching, tutoring, enrichment, or supporting families who homeschool.",
    become: "A homeschool pod can become a small, intentional learning environment for families who want connection, structure, support, or enrichment outside of traditional school.",
    phase1: "Your first step is to define the age range, learning focus, schedule, parent expectations, pricing, location, and policies.",
  },
  nanny_style_care: {
    why: "This pathway fits someone who prefers caring for one family or a very small number of children in a more private setting.",
    become: "Nanny-style care can become a steady private-care income path with clear expectations, written agreements, defined hours, payment structure, and boundaries.",
    phase1: "Your first step is to define the care location, schedule, family expectations, payment, responsibilities, time off, emergency procedures, and written agreement.",
  },
};

// ─── BLUEPRINT CONTENT FOR QUIZ RESULT PAGE ─────────────────────────────────
export const PATHWAY_BLUEPRINT_CONTENT = {
  home_daycare_nursery: {
    tags: ["Steady Monthly Income", "Small Group Care", "Home-Based Rhythm"],
    shortDescription: "A calm, structured home-based childcare path for building steady income, deep family relationships, and a simple daily rhythm.",
    snapshot: {
      bestFor: "Mothers who want consistent care, recurring income, and a close relationship with a small group of families.",
      incomeStyle: "Steady, recurring monthly tuition paid in advance by your enrolled families.",
      programRhythm: "Full-time or consistent weekly care built around your home and family flow.",
      setupFocus: "Licensing, insurance, policies, space setup, pricing, and parent communication.",
    },
    definition: "A home daycare or nursery is a small, consistent childcare program run from your home, usually serving the same families on a recurring weekly schedule.",
    inRealLife: [
      "A small group of children enrolled on a weekly schedule",
      "A calm home rhythm with meals, play, rest, outside time, and connection",
      "Recurring tuition from families creating predictable monthly income",
      "A warm alternative to larger childcare centers",
    ],
    thisIsNot: [
      "Recreating a corporate center or formal classroom inside your home",
      "Needing expensive overhead or a perfect setup to begin exploring",
      "A commitment you have to figure out completely before getting support",
    ],
    bestWhen: [
      "You want stable, recurring monthly income",
      "You enjoy consistency and a structured daily flow",
      "You want deeper relationships with a small group of families",
      "You want your business woven into your family's daily life",
    ],
    whyFits: [
      "Your answers suggest you are drawn to consistent, relationship-based care with local families.",
      "This model can support steady monthly income when structured well with the right enrollment approach.",
      "It works beautifully when you want a childcare business that fits into your home rhythm rather than disrupting it.",
    ],
    whatADayLooksLike: [
      "8:30 AM — Warm morning arrivals and child-led discovery time",
      "9:30 AM — Cozy circle time with storytelling, music, and gentle rhythm",
      "10:00 AM — Shared morning snack followed by outdoor or backyard play",
      "11:30 AM — Calm transition back inside for lunch and wind-down prep",
      "12:30 PM — Quiet rest, reading, and nap windows for little ones",
      "3:00 PM — Gentle afternoon play, sensory activities, and clean-up",
      "4:30 PM — Family pickup, warm connection, and sharing about the day",
    ],
    whatFamiliesValue: [
      "A consistent, dedicated spot in a small, boutique-style home nursery",
      "Warm, personal attention inside a calm and safe home environment",
      "Reliable, long-term care built on trust and a familiar routine",
      "A developmental play rhythm that feels more personal than a larger center",
    ],
    commonFears: [
      { title: "I don't have a perfect house", body: "Families value a warm, loving home over a formal classroom. Simple, clean, and safe spaces are more than enough to begin." },
      { title: "Licensing feels overwhelming", body: "Licensing requirements vary by location, but the process is usually a step-by-step safety checklist. Mama Launch helps you understand what applies to you." },
      { title: "I don't know if my space is ready", body: "Space readiness is something you can build toward. Starting with clarity about your model comes first — space planning follows naturally." },
    ],
    firstSteps: [
      "Review your local family home capacity guidelines and licensing information",
      "Map out your main indoor play, rest, and nap zones at home",
      "Draft your ideal weekly schedule and daily rhythm ideas on paper",
    ],
    couldThisWork: "You do not need a perfect house, a dedicated playroom, or a complete business plan to begin exploring this pathway. What matters first is clarity around your model, your schedule, your boundaries, and your safety plan. Mama Launch helps you build this step by step so it feels organized and supported.",
    outcomes: [
      "A calm, cozy home nursery that genuinely serves your local community",
      "A sustainable, lower-overhead childcare business built around your life",
      "Deep, meaningful relationships with the families you serve week after week",
    ],
    phase1: [
      "Choose your core home nursery model, ages, and care approach",
      "Define your schedule, capacity, and daily rhythm",
      "Map your home space layout for safe, comfortable play and rest",
      "Set your pricing, policies, and parent enrollment expectations",
      "Confirm your licensing pathway, insurance, and business protection steps",
    ],
  },

  part_time_nursery: {
    tags: ["Part-Time Structure", "Morning Play Rhythm", "Balanced Week"],
    shortDescription: "A warm, part-time morning program offering structure and early play for mothers who want income and balance.",
    snapshot: {
      bestFor: "Mothers seeking a focused morning program, predictable days, and afternoons free for their own family.",
      incomeStyle: "Consistent monthly tuition based on 2, 3, or 5 morning-per-week schedules.",
      programRhythm: "Part-time morning hours (e.g., 8:30 AM–12:30 PM) following a school-year rhythm.",
      setupFocus: "Daily schedules, cozy play setups, simple pricing, and parent expectations.",
    },
    definition: "A part-time nursery is a smaller childcare program that runs on limited days or shorter hours, often mornings or a few days per week.",
    inRealLife: [
      "Operating 2 to 4 mornings per week with consistent drop-off times",
      "A small group of toddlers or preschoolers in a gentle morning rhythm",
      "Simple play, wholesome snack, outdoor time, and early learning",
      "Families paying monthly tuition for a reliable part-time spot",
    ],
    thisIsNot: [
      "Full-time daycare with long hours and complex nap management",
      "A commitment to being open five full days every single week",
      "Sacrificing your afternoons or giving up personal family time",
    ],
    bestWhen: [
      "You want income but need clear boundaries around your hours",
      "You like structure but not the weight of full-time care hours",
      "Families in your area are looking for quality part-time options",
      "You want a calm, manageable schedule you can sustain long-term",
    ],
    whyFits: [
      "Your answers suggest you value structure alongside meaningful personal time.",
      "This model can support steady income through monthly tuition while protecting your afternoons.",
      "It serves families looking for trusted, part-time socialization and early learning for their children.",
    ],
    whatADayLooksLike: [
      "8:30 AM — Peaceful transition, arrivals, and table-top morning play",
      "9:15 AM — Cozy morning meeting, storybook time, and daily helper routine",
      "9:45 AM — Wholesome group snack and sensory or art exploration",
      "10:30 AM — Outdoor play, sensory gardens, or neighborhood walk",
      "11:45 AM — Closing circle, reflection, sharing, and song",
      "12:30 PM — Parent pickup, leaving your afternoon completely free",
    ],
    whatFamiliesValue: [
      "Reliable, structured socialization and play before kindergarten",
      "Peace of mind knowing their child is in a small, trusted neighborhood program",
      "A consistent morning routine that supports parents' work, study, or rest",
    ],
    commonFears: [
      { title: "Will families pay enough for part-time?", body: "Many families are actively looking for quality part-time programs, and overhead stays low when your hours are limited." },
      { title: "Do I need an educational background?", body: "No formal degree is required. A nurturing environment, safe space, and thoughtful guided play are what families genuinely value." },
    ],
    firstSteps: [
      "Outline your core activity ideas and preferred morning schedule",
      "Determine your operating days (e.g., Tues/Thurs or Mon/Wed/Fri)",
      "Review any part-time licensing guidelines that apply to your location",
    ],
    couldThisWork: "You do not need a formal education certificate or a dedicated classroom to run a warm morning nursery. By setting clear hours and a simple rhythm, you create a lovely morning flow while preserving your afternoons. Mama Launch helps you design your program step by step.",
    outcomes: [
      "A trusted, cozy neighborhood nursery alternative families return to",
      "A simple, low-overhead morning business that fits your life",
      "A peaceful early learning space built with genuine intention",
    ],
    phase1: [
      "Outline your morning activity flow and simple play schedule",
      "Define your ages, days per week, and comfortable capacity",
      "Draft a basic parent handbook and enrollment agreement",
      "Set your monthly tuition and enrollment expectations",
      "Confirm your local licensing pathway for part-time care",
    ],
  },

  drop_in_care: {
    tags: ["Flexible Booking", "On-Demand Model", "Neighborhood Support"],
    shortDescription: "A flexible, on-demand backup care option helping local families find trusted coverage for appointments, work, and unexpected gaps.",
    snapshot: {
      bestFor: "Providers who love flexibility, enjoy variety, and want to serve families in their neighborhood.",
      incomeStyle: "Hourly drop-in rates or pre-paid multi-hour care passes.",
      programRhythm: "On-demand, flexible scheduling managed on your own terms.",
      setupFocus: "Booking system, parent policies, home capacity guidelines, and intake forms.",
    },
    definition: "Drop-in care is flexible childcare offered by the hour, day, or session for families who need occasional help.",
    inRealLife: [
      "Backup care when schools are closed or regular daycares are unavailable",
      "A few hours of care while a parent works, rests, or attends appointments",
      "Flexible booking windows based on your availability",
      "Occasional care slots rather than permanent weekly enrollment",
    ],
    thisIsNot: [
      "An open-door, always-available arrangement without clear boundaries",
      "Being on-call at all hours or available for every last-minute request",
      "A chaotic model — good policies keep this structured and peaceful",
    ],
    bestWhen: [
      "You enjoy variety and hosting different children throughout your week",
      "Families in your area are looking for flexible backup care options",
      "You want to choose your available days and set your own schedule",
      "You are comfortable setting clear booking, cancellation, and health guidelines",
    ],
    whyFits: [
      "Your answers suggest you prefer variety and flexibility over a fixed weekly enrollment.",
      "Many families are looking for trusted backup care options in their neighborhoods.",
      "This model may be a lower-barrier starting point depending on your local licensing rules.",
    ],
    whatADayLooksLike: [
      "9:00 AM — Arrival window, welcoming drop-in guests, and child intake",
      "10:00 AM — Open-ended play and simple group activities",
      "11:00 AM — Sensory play or active outdoor time",
      "12:00 PM — Wholesome lunch and calm reading area",
      "1:00 PM — Quiet rest or calm independent play",
      "3:00 PM — Afternoon snack and family pickup window",
    ],
    whatFamiliesValue: [
      "Flexible, reliable childcare coverage they can trust on short notice",
      "A safety net during work deadlines, appointments, or school closures",
      "A warm home environment rather than a corporate drop-in center",
    ],
    commonFears: [
      { title: "What if bookings are unpredictable?", body: "Setting a simple weekly availability calendar and advance booking policy creates clear structure — you stay in control of your schedule." },
      { title: "Will it feel chaotic?", body: "Strong parent policies, clear check-in rules, and a daily capacity limit keep things calm and manageable." },
    ],
    firstSteps: [
      "Set your capacity limits (e.g., maximum children at one time)",
      "Choose your preferred operating hours and booking windows",
      "Review your local guidelines around drop-in and backup care arrangements",
    ],
    couldThisWork: "Flexible care works best when you control your availability clearly. You decide when you are open, how many spots exist, and what guidelines protect your home and your time. Mama Launch helps you set up these boundaries so everything runs with clarity.",
    outcomes: [
      "A go-to trusted backup care option for families in your neighborhood",
      "A flexible childcare business where you set your own available days",
      "A meaningful way to support busy local families with real care needs",
    ],
    phase1: [
      "Define your available days, hours, and booking approach",
      "Set your daily child capacity and safety ratios",
      "Draft parent intake and emergency authorization forms",
      "Set your pricing and booking cancellation policies",
      "Confirm your insurance and home protection needs",
    ],
  },

  kids_classes: {
    tags: ["Enrichment Sessions", "Creative Short Blocks", "Community Play"],
    shortDescription: "A creative, session-based enrichment program offering sensory play, art, music, or developmental workshops in short, focused blocks.",
    snapshot: {
      bestFor: "Creative mothers and educators who want to teach without full-day childcare logistics.",
      incomeStyle: "Drop-in class passes or multi-week seasonal cohort packages.",
      programRhythm: "Short, engaging 60–90 minute sessions scheduled throughout the week.",
      setupFocus: "Curriculum planning, simple materials, venue coordination, and class pricing.",
    },
    definition: "Kids classes are short enrichment sessions built around a specific activity, skill, or theme.",
    inRealLife: [
      "Sensory play, messy art, or creative nature exploration classes",
      "Music, rhythm, movement, and toddler storytime sessions",
      "Seasonal crafts, themed workshops, or weekend pop-up events",
      "60–90 minute sessions where children create, move, and learn",
    ],
    thisIsNot: [
      "Full-day childcare with meal routines, naps, or licensing requirements for centers",
      "A commitment to the same families every single week through formal enrollment",
      "A business that requires a dedicated space or large upfront investment",
    ],
    bestWhen: [
      "You love planning themed play, crafts, or sensory experiences",
      "You prefer energetic, short sessions over full-day care responsibilities",
      "You want creative flexibility to rotate themes and activities each season",
      "You want to serve many families with a lower administrative commitment",
    ],
    whyFits: [
      "Your answers suggest you are drawn to creative, activity-based work with children.",
      "Classes let you design engaging programs without nap schedules or complex licensing steps.",
      "Outdoor parks, community rooms, or church halls can work beautifully as hosting spaces.",
    ],
    whatADayLooksLike: [
      "9:30 AM — Set up messy play tables, sensory trays, and clean-up stations",
      "10:00 AM — Welcome families, brief circle song, and theme introduction",
      "10:15 AM — Active sensory station rotation and creative child play",
      "11:00 AM — Group storybook tie-in and gentle clean-up transition",
      "11:15 AM — Closing connection, parent handouts, and warm pickups",
      "11:30 AM — Quick reset, leaving the rest of your day free",
    ],
    whatFamiliesValue: [
      "Beautifully prepared activities they don't have to plan or clean up at home",
      "Thoughtful developmental themes and age-appropriate guidance",
      "Connection with other neighborhood families in a joyful, low-pressure space",
    ],
    commonFears: [
      { title: "What if I don't have a venue?", body: "Classes are mobile-friendly. Community rooms, local parks, and outdoor yards are all viable hosting spaces depending on your local guidelines." },
      { title: "Is income from classes reliable?", body: "Packaging classes into multi-week series with upfront payment helps create more predictable income compared to single-session drop-in only." },
    ],
    firstSteps: [
      "Outline your favorite class themes or a 4–6 week enrichment series idea",
      "Confirm your preferred ages, session length, and hosting location",
      "Set your per-seat pricing and draft a simple booking approach",
    ],
    couldThisWork: "Classes are one of the more accessible ways to begin because you don't necessarily need a licensed facility or permanent space. You prep, host, and welcome parents. Mama Launch helps you outline your themes, pricing, and simple booking tools so you can build with clarity.",
    outcomes: [
      "A beloved neighborhood enrichment program families look forward to",
      "A lower-overhead offering with flexibility to grow and scale over time",
      "A warm community hub that brings local mothers and children together",
    ],
    phase1: [
      "Outline your signature 6-week class or enrichment theme",
      "Confirm your ages, session length, and location setup",
      "Source materials and set your per-class pricing",
      "Draft your booking, payment, and cancellation approach",
      "Review any local guidelines for class-based programs",
    ],
  },

  mommy_and_me: {
    tags: ["Parent Present", "Village Building", "Community Centered"],
    shortDescription: "A parent-inclusive class designed to nurture young children while building meaningful community for mothers and caregivers.",
    snapshot: {
      bestFor: "Moms who love hosting, building community circles, and supporting early mother-child connection.",
      incomeStyle: "Multi-week class series passes or per-session caregiver tickets.",
      programRhythm: "Warm 60–75 minute weekly sessions holding space for play and parent connection.",
      setupFocus: "Warm hosting layout, simple session themes, and registration.",
    },
    definition: "A Mommy & Me program is a parent-child class where the caregiver stays and participates with the child.",
    inRealLife: [
      "Weekly parent-child play circles and gentle maternal support gatherings",
      "Guided songs, simple stories, and sensory play moments",
      "Holding space for moms to share honestly about feeding, sleep, and life",
      "Building a local motherhood community where caregivers find real connection",
    ],
    thisIsNot: [
      "Drop-off childcare where parents leave their children in your care alone",
      "Full safety responsibility for children without parents present",
      "A rigid classroom or academic early childhood program",
    ],
    bestWhen: [
      "You are passionate about creating safe, welcoming spaces for mothers",
      "You want to build meaningful local community around early childhood",
      "You prefer parent-present structures with simpler administrative steps",
      "You want a gentle business model that honors connection over complexity",
    ],
    whyFits: [
      "Your answers suggest you are passionate about connection, community, and supporting mothers.",
      "Because parents stay with their children, administrative and licensing steps tend to be simpler.",
      "This creates a safe, nurturing space for guided play and mother-to-mother support.",
    ],
    whatADayLooksLike: [
      "9:45 AM — Lay down soft rugs, floor cushions, and baby-safe toys",
      "10:00 AM — Welcome mothers with tea or coffee and a warm circle",
      "10:15 AM — Gentle welcome song, storybook time, and sensory discovery",
      "10:45 AM — Guided maternal discussion on postpartum topics or child play",
      "11:15 AM — Closing song circle and warm, unhurried departures",
    ],
    whatFamiliesValue: [
      "Maternal connection, validation, and a safe space to share openly",
      "Guided early play and gentle socialization for infants and toddlers",
      "A circle of nearby parent friends who understand their season of life",
    ],
    commonFears: [
      { title: "Am I qualified enough to hold this space?", body: "You don't need to be a licensed therapist. Being a warm, present, fellow mother is genuinely what many families are looking for." },
      { title: "Will mothers pay for this?", body: "Many families are looking for exactly this kind of connection and community — it addresses a real need for mothers in the postpartum and early childhood season." },
    ],
    firstSteps: [
      "List 4–6 warm session topics you feel genuinely excited to explore",
      "Design a cozy, sensory-safe floor layout in your home or hosted space",
      "Decide on your maximum group size and simple weekly schedule",
    ],
    couldThisWork: "Mommy & Me classes are wonderful because parents stay. This removes most drop-off supervision steps and lets you focus completely on connection, warmth, and village-building. Mama Launch helps you lay out your space and session circles so mothers feel immediately at home.",
    outcomes: [
      "A warm, mother-centered modern village right in your neighborhood",
      "A gentle, accessible business model that can grow through word of mouth",
      "A meaningful space that blends children's play and parent community",
    ],
    phase1: [
      "Choose your weekly themes and simple session flow",
      "Set up a warm, safe sensory space in your home or hosted venue",
      "Define your ages, group size, and caregiver role",
      "Set your pricing and simple signup process",
      "Launch an interest list with local neighborhood mothers",
    ],
  },

  playgroup_open_play: {
    tags: ["Open Play Hub", "Community Rhythm", "Low-Key Hosting"],
    shortDescription: "A welcoming open playgroup model where children explore freely, parents connect, and neighborhood community grows organically.",
    snapshot: {
      bestFor: "Natural hosts who want a low-pressure format where children socialize and parents breathe.",
      incomeStyle: "Drop-in session fees or simple monthly family membership passes.",
      programRhythm: "Set open-play hours (e.g., Tuesday and Thursday mornings) with a relaxed pace.",
      setupFocus: "Space safety, basic family guidelines, simple signup forms, and community outreach.",
    },
    definition: "A playgroup or open play model gives families a safe, welcoming space to gather, play, and connect.",
    inRealLife: [
      "Cozy open play mornings with open-ended toys and safe play spaces",
      "Parent-supervised social play where children learn from each other",
      "Seasonal play sessions, backyard gatherings, or morning community meetups",
      "Simple session passes or neighborhood membership options for regular families",
    ],
    thisIsNot: [
      "Structured, minute-by-minute teaching or formal curriculum sessions",
      "Full-day childcare with nap schedules or sole supervision responsibility",
      "Drop-off care where you manage all children without parents present",
    ],
    bestWhen: [
      "You are a natural host who loves bringing local families together",
      "You want a low-pressure model that respects child-led discovery",
      "You want to socialize your own kids alongside neighborhood friends",
      "You prefer community building over structured preschool curriculums",
    ],
    whyFits: [
      "Your answers suggest you prefer open, child-led play over formal instruction.",
      "This structure allows parents to connect while children play in a cozy home setting.",
      "It tends to require less intensive daily prep compared to structured classes.",
    ],
    whatADayLooksLike: [
      "9:00 AM — Set up open play spaces and a small coffee or tea station",
      "9:30 AM — Welcome parents, self-guided open play begins",
      "10:30 AM — Gentle transition, brief clean-up helper, and shared snack",
      "11:00 AM — Closing circle with a song or simple seasonal activity",
      "11:30 AM — Tidy up and enjoy your afternoon",
    ],
    whatFamiliesValue: [
      "A clean, welcoming space filled with beautiful play materials and setups",
      "Conversation and connection with nearby mothers in a calm environment",
      "A consistent weekly routine that breaks up the week for little ones",
    ],
    commonFears: [
      { title: "What if my home gets messy?", body: "Selecting open-ended wooden toys and setting clear play zone guidelines keeps clean-up manageable and your space protected." },
      { title: "How do I find families?", body: "Word of mouth among local mothers tends to spread quickly when the space feels warm, safe, and genuinely welcoming." },
    ],
    firstSteps: [
      "Choose 2 mornings per week you would enjoy hosting open play",
      "Draft 3–4 simple space guidelines for families to follow",
      "Set your session pricing and comfortable child capacity limit",
    ],
    couldThisWork: "Open play is popular because it is simple, cozy, and community-driven. You are not running a formal class — you are welcoming families to play and connect. Mama Launch helps you structure your guidelines, space setup, and parent expectations so you feel protected and at ease.",
    outcomes: [
      "A beloved morning play sanctuary for young local families",
      "A gentle community business woven into your children's daily rhythm",
      "A neighborhood hub that grows through genuine relationship and trust",
    ],
    phase1: [
      "Select safe, open-ended play materials and organize your space",
      "Establish simple parent supervision guidelines",
      "Define your open-play hours, capacity, and age range",
      "Set your pricing and session registration approach",
      "Review any basic safety and home liability considerations",
    ],
  },

  homeschool_pod: {
    tags: ["Small Group Learning", "Educator Freedom", "School-Age Focus"],
    shortDescription: "A close-knit, relationship-centered learning pod offering personalized pacing and curriculum freedom for school-age children.",
    snapshot: {
      bestFor: "Educators and homeschool mothers who want small-group teaching setups and curriculum flexibility.",
      incomeStyle: "Predictable monthly tuition or set annual learning shares per family.",
      programRhythm: "Dedicated learning hours (e.g., 9 AM–2 PM), running 3 to 4 days per week.",
      setupFocus: "Curriculum selection, local guidelines, safety planning, and family alignment.",
    },
    definition: "A homeschool pod is a small learning group that supports school-aged children with structure, enrichment, tutoring, or shared learning.",
    inRealLife: [
      "Small-group educational days focused on individual learning rhythms",
      "Enrichment blocks with nature walks, science projects, or literature studies",
      "Tutoring-style sessions helping children strengthen reading and math",
      "A close social circle for school-aged homeschool children learning together",
    ],
    thisIsNot: [
      "Recreating a traditional 30-student institutional classroom experience",
      "Opening a full, complex private school with formal accreditation",
      "Needing to teach every advanced subject yourself without any outside resources",
    ],
    bestWhen: [
      "You have a background or genuine love for teaching or guiding children",
      "You want educational flexibility to teach what truly matters to you",
      "You want to support school-aged kids and homeschool families in your area",
      "You want a structured, rewarding business model you can shape yourself",
    ],
    whyFits: [
      "Your answers suggest you are drawn to structured learning and working with school-age children.",
      "Families who value small, personalized learning environments are often actively seeking this kind of pod.",
      "It offers genuine curriculum freedom while honoring a teaching or education background.",
    ],
    whatADayLooksLike: [
      "9:00 AM — Arrival, warm check-in, and review of the day's learning goals",
      "9:30 AM — Focused core math, reading, or science work with tailored support",
      "11:00 AM — Creative project work, crafting, or historical exploration",
      "12:00 PM — Wholesome lunch and active outdoor or backyard learning",
      "1:00 PM — Group reading, journaling, or creative writing session",
      "2:00 PM — Simple daily review, clean-up, and parent pickup transition",
    ],
    whatFamiliesValue: [
      "An excellent student-to-teacher ratio and highly personalized learning",
      "Educational flexibility that allows their child to move at their own pace",
      "A warm, trusted learning community with clear structure and intention",
    ],
    commonFears: [
      { title: "What about state or local laws?", body: "Home education guidelines vary by location, but many areas are highly supportive of small learning pods. Mama Launch helps you understand what applies to you." },
      { title: "Do I need to buy expensive curriculum?", body: "There are many beautiful, pre-made homeschool curriculum options at accessible price points that can guide your daily lessons with ease." },
    ],
    firstSteps: [
      "Define your preferred student age range and core learning values",
      "Review the home education and small-group learning guidelines in your state",
      "Outline your curriculum interests and a rough weekly roadmap",
    ],
    couldThisWork: "Homeschool pods are in growing demand because families want small, trusted learning environments. Licensing requirements vary by location, and Mama Launch helps you understand what applies to your specific area. You don't have to figure this out alone.",
    outcomes: [
      "A trusted, relationship-centered learning pod families believe in deeply",
      "Meaningful academic growth and confidence for your students",
      "A satisfying, flexible teaching rhythm you design around your strengths",
    ],
    phase1: [
      "Define your student age range and learning philosophy",
      "Confirm local guidelines for small-group homeschool learning arrangements",
      "Outline your core curriculum resources and weekly rhythm",
      "Set your tuition, schedule, and enrollment agreements",
      "Establish family communication and learning accountability expectations",
    ],
  },

  nanny_style_care: {
    tags: ["Intimate Care", "Private Family Support", "Calm Daily Rhythm"],
    shortDescription: "A private, relationship-centered care arrangement focused on deep trust, steady income, and a simple daily rhythm with one family.",
    snapshot: {
      bestFor: "Mothers and providers who thrive in quiet, high-trust, one-family home environments.",
      incomeStyle: "Stable weekly retainer arrangements or direct family care contracts.",
      programRhythm: "Tailored full-day or part-time schedule centered on one family's home and routine.",
      setupFocus: "Written agreements, child routines, safety protocols, and parent communication.",
    },
    definition: "Nanny-style care is a private care arrangement, usually for one family or a very small number of children.",
    inRealLife: [
      "Caring for one family's baby, toddler, or siblings with dedicated focus",
      "Working in your home or their home depending on the agreement and local guidelines",
      "A consistent weekly schedule with predictable hours and familiar routines",
      "A professional written care agreement securing your schedule and compensation",
    ],
    thisIsNot: [
      "Managing multiple families, conflicting schedules, or group care logistics",
      "Needing a licensed facility setup or formal classroom arrangement",
      "Building a large program or managing a group of children on your own",
    ],
    bestWhen: [
      "You prefer quiet, focused care days with one child or sibling pair",
      "You want to manage one parent relationship and one set of family expectations",
      "You value building deep, lasting bonds of trust and ongoing care",
      "You want a simpler starting point with a lower administrative footprint",
    ],
    whyFits: [
      "Your answers suggest you are drawn to quiet, personal care with a small number of families.",
      "This model avoids group management, and may require fewer complex licensing steps depending on your location.",
      "It can support steady, reliable income when structured with clear agreements and expectations.",
    ],
    whatADayLooksLike: [
      "8:30 AM — Warm parent arrival, brief morning update, and gentle transition",
      "9:00 AM — Cozy reading corner, floor play, and baby sensory exploration",
      "10:00 AM — Wholesome snack and a neighborhood stroller walk or park visit",
      "11:30 AM — Return home, lunch preparation, and peaceful nap routine",
      "1:30 PM — Gentle waking, afternoon play, and music or movement exploration",
      "3:00 PM — Backyard play, cozy reading, and clean-up reset",
      "4:30 PM — Parent pickup, warm daily review, and peaceful closing",
    ],
    whatFamiliesValue: [
      "Complete, dedicated attention focused entirely on their child's safety and growth",
      "A deeply personalized schedule that matches their infant or toddler's needs",
      "Consistency, familiarity, and a quiet home environment they can trust",
    ],
    commonFears: [
      { title: "How do I protect my income and time?", body: "A clear, professional written agreement with set weekly hours and a retainer structure helps secure your compensation and boundaries." },
      { title: "Will I feel isolated in a one-family arrangement?", body: "Planning outdoor outings, joining local park playdates, and building seasonal rhythms keeps your days varied and socially rich." },
    ],
    firstSteps: [
      "Set your weekly care rate and define your care hours and availability",
      "Decide whether care will take place in your home or the family's home",
      "Confirm your current infant or child CPR and first-aid certifications",
    ],
    couldThisWork: "Private family care is peaceful because you focus entirely on one relationship. Licensing requirements for this arrangement vary by location and structure, so Mama Launch helps you understand what applies to you. You don't need a daycare setup — you need clarity and a clear written agreement.",
    outcomes: [
      "A trusted, deeply relationship-centered private care arrangement",
      "A calm and predictable daily routine built around real life",
      "Freedom to design meaningful outdoor routines, simple meals, and gentle daily rhythms",
    ],
    phase1: [
      "Draft a clear, fair private-care agreement template",
      "Confirm your child CPR and first-aid certifications",
      "Define your schedule, availability, and time-off expectations",
      "Set your weekly rate and payment structure",
      "Clarify your care responsibilities and home boundaries",
    ],
  },
};